version: '3'
services:
  postgres:
    image: postgres:13.0
    container_name: DZ_postgres
    environment:
       POSTGRES_DB: postgres
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: 12345
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - C:/Users/serpo/Downloads/backups:/backups
